SEARCH_CLASSIFIER_USER_INPUTS = [
    "Hey",
    "What's the weather in new york?",
    "good morning",
    "how did the giants play yesterday",
    "I'm hungry",
    "how can i reverse a list in python",
    "what is a fibonacci sequence",
    "what are recent news about AI",
    "what's the current apple stock price",
    "thanks, that's helpful",
    "what's the latest in machine learning?",
    "how to make a cake?",
    "tell me a joke",
    "what's the time?",
    "how's the weather today?",
    "what's the latest news about the pandemic?",
    "what's the highest mountain in the world?",
    "who won the last world cup?",
    "how to lose weight?",
    "what's the capital of Australia?",
    "who is the president of the United States?",
    "how to make pizza at home?",
    "tell me a fun fact",
    "what's the distance to the moon?",
    "What's the latest movie by Christopher Nolan?",
    "How to fix a leaky faucet?",
    "Who is the current CEO of Tesla?",
    "What are the symptoms of the flu?",
    "What events are happening in Paris this weekend?",
    "How do I reset my iPhone?",
    "What's the exchange rate for euros to dollars today?",
    "What are the top ten books this year?",
    "How to meditate effectively?",
    "When is the next solar eclipse?",
    "What are the new features in the latest Android update?",
    "How to improve my credit score?",
    "What's the recipe for a margarita?",
    "When is the next SpaceX launch scheduled?",
    "What are the best practices for sustainable living?",
    "How to write a resignation letter?",
    "What's the population of Canada?",
    "Latest trends in interior design?",
    "How to reduce carbon footprint at home?",
    "What are the health benefits of yoga?",
    "When is the international space station visible tonight?",
    "How to train for a marathon?",
    "What's happening in the stock market today?",
    "How to deal with anxiety?",
    "What's the best way to learn a new language?",
    "When was the Eiffel Tower built?",
    "What are the upcoming tech conferences?",
    "How to make homemade ice cream?",
    "What's the current situation in Ukraine?",
    "How to start a small business?",
    "What are the latest scientific discoveries?",
    "How to get rid of ants naturally?",
    "What are the current travel restrictions?",
    "What's the best diet for weight loss?",
    "When is the next Olympic Games?",
    "How to change a car tire?",
    "What's the latest in renewable energy?",
    "How to make a budget?",
    "What's the cure for a common cold?",
    "What are the new rules in the NBA?",
    "How to improve sleep quality?",
    "What's the price of Bitcoin today?",
    "How to write a business plan?",
    "What are the UNESCO World Heritage sites?",
    "How to cook a vegan meal?",
    "What's the latest on Mars missions?",
    "How to clean a laptop screen?",
    "What are the side effects of this medication?",
    "What's the best smartphone right now?",
    "How to organize a charity event?",
    "How to install solar panels at home?",
    "What's the latest update on climate change?",
    "Who won the Nobel Prize in Literature last year?",
    "What are the visa requirements for traveling to Japan?",
    "How to do a handstand?",
    "What are the best local restaurants in Rome?",
    "How to create a podcast?",
    "When is the next lunar eclipse?",
    "What are effective strategies for time management?",
    "How to prepare for a job interview?",
    "What's the speed of light?",
    "Latest advancements in artificial intelligence?",
    "How to reduce plastic waste in daily life?",
    "What are the top-rated tourist attractions in Egypt?",
    "How to fix a slow computer?",
    "What are the symptoms of vitamin D deficiency?",
    "When is the next Formula 1 race?",
    "How to grow your own vegetables?",
    "What are the best practices for cybersecurity?",
    "How to improve air quality indoors?",
    "What are the latest advancements in electric vehicles?",
    "How to make sourdough bread at home?",
    "What are the historical landmarks to visit in Berlin?",
    "How to optimize Wi-Fi performance at home?",
    "What are the health effects of intermittent fasting?",
    "When is the next total solar eclipse visible in North America?",
]
